namespace StarlightGUI
{
    struct DataPoint
    {
        Double X;
        Double Y;
    };
    
    [default_interface]
    runtimeclass LineGraphControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        LineGraphControl();
        
        String Title { get; set; };
        Boolean ShowGrid { get; set; };
        Boolean ShowLegend { get; set; };
        Boolean EnableZoom { get; set; };
        
        void AddSeries(String name, Windows.UI.Color color);
        void AddDataPoint(String seriesName, Double x, Double y);
        void ClearSeries(String seriesName);
        void ClearAllSeries();
        void ZoomToFit();
        void ResetView();
        void SetSeriesColor(String seriesName, Windows.UI.Color color);
        void SetSeriesVisibility(String seriesName, Boolean visible);
        void SetSeriesThickness(String seriesName, Double thickness);
    }
}