namespace StarlightGUI
{
    [default_interface]
    runtimeclass LoadDriverDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        LoadDriverDialog();
        String DriverPath{ get; };
        Boolean Bypass{ get; };
    }
}
