namespace StarlightGUI
{
    [default_interface]
    runtimeclass UpdateDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        UpdateDialog();

        Boolean IsUpdate{ get; set; };
        String LatestVersion{ get; set; };
        String Announcement{ get; set; };
    }
}
