namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass KernelModuleInfo
	{
		KernelModuleInfo();

		String Name{ get; set; };
		String Path{ get; set; };
		String ImageBase{ get; set; };
		UInt64 ImageBaseULong{ get; set; };
		String Size{ get; set; };
		UInt64 SizeULong{ get; set; };
		String DriverObject{ get; set; };
		UInt64 DriverObjectULong{ get; set; };
	}
}