namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass ProcessInfo
	{
		ProcessInfo();

		Int32 Id{ get; set; };
		String Name{ get; set; };
		String Description{ get; set; };
		String MemoryUsage{ get; set; };
		UInt64 MemoryUsageByte{ get; set; };
		String CpuUsage{ get; set; };
		String ExecutablePath{ get; set; };
		String EProcess{ get; set; };
		UInt64 EProcessULong{ get; set; };
		Microsoft.UI.Xaml.Media.ImageSource Icon{ get; set; };
	}
}